//agent// rdf:type owl:NamedIndividual .
//taskexec// rdf:type oasis:TaskExecution .
//taskexec// oasis:hasTaskObject //taskexeobject// .
//taskexeobject// rdf:type oasis:TaskObject .
//taskexeobject// oasis:refersExactlyTo //theobject// .
//theobject// oasis:hasType ?oElemType .
//taskexec// oasis:hasTaskOperator //taskexeoperator// .
//taskexeoperator// rdf:type oasis:TaskOperator .
//taskexeoperator// oasis:refersExactlyTo //param2// .