Select ?confProp ?featProp ?featValue
WHERE
{   
   ?task oasis:hasTaskObject ?taskObject .   
   ?taskObject ?referObj ?taskObElement .
   ?taskObElement a oasis:ReferenceTemplate .
   FILTER (?referObj =  oasis:refersExactlyTo || ?referObj =  oasis:refersAsNewTo)
   ?taskObElement ?confProp ?confValue.
   ?confValue a oasis:ReferenceTemplate .
   FILTER(?confProp !=oasis:hasType && ?confProp!=rdf:type)
   FILTER NOT EXISTS
   {
       ?confProp rdfs:subPropertyOf oasis:hasType.    
   }  
   ?confValue ?featProp ?featValue.
   FILTER(?featProp!=rdf:type)
}