{
?tasko oasis:refersExactlyTo ?taskoElem .
}
UNION
{
 ?tasko oasis:refersAsNewTo ?taskoElem .	
}
OPTIONAL #actuator
{
 //agent// oasis:settles ?actuator.
 ?actuator oasis:adoptsActuatorTemplate ?taskoElem.
}