{
?taskd oasis:hasTaskFormalInputParameter ?taskInpParam.
}
UNION
{
?taskd oasis:hasTaskInputParameterTemplate ?taskInpParam.	
}

{
?taskInpParam oasis:refersExactlyTo ?taskInpElem .
}
UNION
{
?taskInpParam oasis:refersAsNewTo ?taskInpElem .	
}

?taskInpElem ?aInpProp ?aInpPropValue.
VALUES ?aInProp {//list1//}